- name: Apply iptables rules
  ansible.builtin.shell: iptables-restore < /etc/iptables/rules.v4
  become: true
  listen: Apply iptables rules
  changed_when: true

- name: Save iptables rules
  ansible.builtin.command: netfilter-persistent save
  become: true
  listen: Save iptables rules
  changed_when: true
