- name: Restart kea-dhcp-ddns-server service
  ansible.builtin.systemd:
    name: kea-dhcp-ddns-server
    enabled: true
    state: restarted
  become: true
  listen: Restart kea-dhcp-ddns-server service
