servers:
  hosts:
    lab_s01_fw:
      ansible_host: 10.120.69.17
      ansible_user: root
    lab_s02_proxy:
      ansible_host: 10.120.69.5
      ansible_user: root
    lab_s03_dhcp_dns:
      ansible_host: 10.120.69.18
      ansible_user: root
    lab_s04_rootca:
      ansible_host: 10.120.69.21
      ansible_user: root

clients:
  hosts:
    lab_c01:
      ansible_host: lab-c01.local.orzehhowski.pl
      ansible_user: root