- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present
    update_cache: true

- name: Put bind options file
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  notify:
    - Restart named service

- name: Put bind main config file
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: '0644'
  notify:
    - Restart named service

- name: Put bind local config file
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
  notify:
    - Restart named service

- name: Put bind forward zone db file
  ansible.builtin.template:
    src: db.local.orzehhowski.pl.j2
    dest: /var/lib/bind/db.local.orzehhowski.pl
    owner: root
    group: bind
    mode: '0644'
  notify:
    - Restart named service

- name: Put bind reverse zone db file
  ansible.builtin.template:
    src: db.10.j2
    dest: /var/lib/bind/db.10
    owner: root
    group: bind
    mode: '0644'
  notify:
    - Restart named service

- name: Ensure the named service is running
  ansible.builtin.include_tasks: tasks/start_and_check_service.yml
  vars:
    service_name: named
