iptables_renders:
  filter:
    input: |
      -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -p udp -m udp --sport 67:68 --dport 67:68 -j ACCEPT
      -A INPUT -i eth2 -p tcp -m tcp --dport 22 -j ACCEPT
      -A INPUT -p icmp -j ACCEPT
      -A INPUT -i lo -j ACCEPT
    forward: |
      -A FORWARD -m state --state RELATED,ESTABLISHED -m comment --comment allow-existing-connections -j ACCEPT
      -A FORWARD -s 10.120.69.16/28 -d 10.120.69.5/32 -i eth1 -o eth0 -p tcp -m tcp --dport 3142 -m comment --comment servers-2-apt-proxy -j ACCEPT
      -A FORWARD -s 10.120.69.32/28 -d 10.120.69.5/32 -i eth2 -o eth0 -p tcp -m tcp --dport 3142 -m comment --comment MGMT-2-apt-proxy -j ACCEPT
      -A FORWARD -d 10.120.69.18/32 -o eth1 -p tcp -m tcp --dport 53 -m comment --comment DNS-TCP -j ACCEPT
      -A FORWARD -s 10.120.69.0/24 -d 10.120.69.22/32 -o eth1 -p tcp -m tcp --dport 51515 -m comment --comment backup-server -j ACCEPT
      -A FORWARD -d 10.120.69.18/32 -o eth1 -p udp -m udp --dport 53 -m comment --comment DNS-UDP -j ACCEPT
      -A FORWARD -s 10.120.69.18/32 -i eth1 -o eth0 -p tcp -m tcp --dport 53 -m comment --comment DNS-RECURSION-TCP -j ACCEPT
      -A FORWARD -s 10.120.69.18/32 -i eth1 -o eth0 -p udp -m udp --dport 53 -m comment --comment DNS-RECURSION-UDP -j ACCEPT
      -A FORWARD -s 10.120.69.80/32 -d 10.120.69.19/22 -i eth5 -o eth1 -p tcp -m tcp --dport 2049 -m comment --comment Clients-2-NFS-data -j ACCEPT
      -A FORWARD -s 10.120.69.80/32 -d 10.120.69.19/22 -i eth5 -o eth1 -p udp -m udp --dport 2049 -m comment --comment Clients-2-NFS-data -j ACCEPT
      -A FORWARD -s 10.120.69.80/32 -d 10.120.69.19/22 -i eth5 -o eth1 -p udp -m udp --dport 111 -m comment --comment Clients-2-NFS-portmapper -j ACCEPT
      -A FORWARD -s 10.120.69.80/32 -d 10.120.69.19/22 -i eth5 -o eth1 -p udp -m udp --dport 111 -m comment --comment Clients-2-NFS-portmapper -j ACCEPT
      -A FORWARD -s 10.120.69.32/28 -d 10.120.69.20/32 -i eth2 -o eth1 -p tcp -m tcp --dport 443 -m comment --comment MGMT-2-APPS-https -j ACCEPT
      -A FORWARD -s 10.120.69.32/28 -d 10.120.69.20/32 -i eth2 -o eth1 -p tcp -m tcp --dport 80 -m comment --comment MGMT-2-APPS-http -j ACCEPT
      -A FORWARD -s 10.120.69.16/28 -i eth1 -o eth0 -p tcp -m multiport --dports 80,443 -m comment --comment "Servers-allow-http[s]" -j ACCEPT
      -A FORWARD -s 10.120.69.80/28 -i eth5 -o eth0 -p tcp -m multiport --dports 80,443 -m comment --comment "Clients-allow-http[s]" -j ACCEPT
      -A FORWARD -d 10.120.69.34/32 -i eth0 -o eth2 -p tcp -m tcp --dport 3389 -m comment --comment RDP-2-MGMT -j ACCEPT
      -A FORWARD -s 10.120.69.34/32 -i eth2 -o eth0 -p tcp -m tcp --dport 443 -m comment --comment MGMT-allow-https -j ACCEPT
      -A FORWARD -s 10.120.69.34/32 -d 10.120.69.3/32 -i eth2 -o eth0 -p tcp -m tcp --dport 8006 -m comment --comment MGMT-2-PROXMOXVE -j ACCEPT
      -A FORWARD -s 10.120.69.34/32 -d 10.120.69.3/32 -i eth2 -o eth0 -m comment --comment MGMT-2-PVE-console -j ACCEPT
      -A FORWARD -s 10.120.69.34/32 -i eth2 -o eth0 -p tcp -m tcp --dport 80 -m comment --comment MGMT-allow-http -j ACCEPT
      -A FORWARD -s 10.120.69.20/32 -i eth1 -o eth0 -p tcp -m tcp --dport 80 -m comment --comment APPS-allow-http -j ACCEPT
      -A FORWARD -s 10.120.69.20/32 -i eth1 -o eth0 -p tcp -m tcp --dport 443 -m comment --comment APPS-allow-https -j ACCEPT
      -A FORWARD -s 10.120.69.34/32 -d 10.120.69.16/28 -i eth2 -o eth1 -p tcp -m tcp --dport 22 -m comment --comment MGMT-2-Servers-SSH -j ACCEPT
      -A FORWARD -s 10.120.69.34/32 -d 10.120.69.0/28 -i eth2 -o eth0 -p tcp -m tcp --dport 22 -m comment --comment MGMT-2-DMZ-SSH -j ACCEPT
      -A FORWARD -s 10.120.69.34/32 -d 10.120.69.96/28 -i eth2 -o eth6 -p tcp -m multiport --dports 80,443 -m comment --comment MGMT-2-WiFi -j ACCEPT
      -A FORWARD -p icmp -m comment --comment allow-icmp -j ACCEPT
      -A FORWARD -i lo -j ACCEPT
      -A FORWARD -o lo -j ACCEPT

dhcp_relay:
  interfaces: "eth1 eth5 eth6"
  options: ""