$ANSIBLE_VAULT;1.1;AES256
63626161393835653638356161663566353265383236623361383063356536356331616137643235
6166366333616136616434323834396133303562386666340a323462623166326532333766633962
37353935393930646535386238653637346339653461373863303439633566663461313335383339
3239303034326363370a373939333466356537383935616164623739393634646161333962303638
63643132363561366663663531376663653639656338353238363661373732313531346361343265
61383766346236323765383836316231396465613332653564333961393838653333373837343937
61323864303531666435626435346633616332306136623965393235396664396263323365356439
65313339393030613435313232336164363639643363363037646431346631323738336565346233
38353438626362336662643366633237373131303533396164616537356162396362393237656330
35393730303564343939616134343439626535333532313636313265393034313233313931633033
61656166396232336434633330323465353964373334366138336334366664333664306361643963
30393833643866613162663137323063393036313932343562313434396139353231666433393033
32336432306366333830663163343065393532393834636637623334396239316230353864653838
3831623233346537396438623662636630636265656462366235
